services:
  - type: web
    name: sentiment-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python dash_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
